
version: "3.3"
services:
  builder:
    build:
      context: ./
      dockerfile: docker/build/Dockerfile
    image: builder:latest

  webserver:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "${WEBSERVER_PORT}:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - mysql
    image: tasklistfpm:latest

  installapp:
    build:
      context: ./
      dockerfile: docker/installapp/Dockerfile
    depends_on:
      - mysql
      - php-fpm

  mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD} 