version: "3.3"
services:
  mysql:
    image: mysql:5.7
    network_mode: host
    environment:
      MYSQL_DATABASE: task-list-test
      MYSQL_USER: secretuser
      MYSQL_PASSWORD: thisisasupersecretpassworddontyouthink
      MYSQL_ROOT_PASSWORD: iamgroot
      MYSQL_TCP_PORT: "3307"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--port=3307"]
      interval: 5s
      timeout: 5s
      retries: 20

  go-e2e-tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    network_mode: host
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER: "127.0.0.1"
      DB_PORT: "3307"
      DB_NAME: task-list-test
      DB_USER: secretuser
      DB_PASSWORD: thisisasupersecretpassworddontyouthink
    command: ["go", "test", "-v", "-count=1", "./tests/e2e/..."]
